// 课程结构（lessonId 与内容文件实际使用的一致）
// level 字段标记所属等级：入门（全体可见）/ 初级等（管理员内测中）
export const curriculum = [
  {
    level: '入门' as const,
    week: 1,
    title: '平台认知与账号安全',
    lessons: [
      'm1-00', 'm1-01-what-is-ops', 'm1-02-account-health',
      'm1-03-violation-notice', 'm1-04-listing-compliance',
      'm1-05-review-compliance', 'm1-06-buyer-messages', 'm1-07-eu-compliance',
    ],
  },
  {
    level: '入门' as const,
    week: 2,
    title: '选品与采购',
    lessons: [
      'm7-01-why-selection-matters', 'm7-02-demand-analysis', 'm7-03-competition-analysis',
      'm7-04-profit-screening', 'm7-05-sourcing', 'm7-06-selection-practice',
    ],
  },
  {
    level: '入门' as const,
    week: 3,
    title: 'Listing搭建基本功',
    lessons: [
      'm2-00', 'm2-01', 'm2-02', 'm2-03', 'm2-03b', 'm2-04',
      'm2-05', 'm2-06', 'm2-07', 'm2-08', 'm2-09', 'm2-10',
    ],
  },
  {
    level: '入门' as const,
    week: 4,
    title: '库存与FBA物流',
    lessons: [
      'm3-01', 'm3-02', 'm3-03', 'm3-04', 'm3-05', 'm3-06', 'm3-07',
    ],
  },
  {
    level: '入门' as const,
    week: 5,
    title: '广告体系',
    lessons: [
      'm4-01', 'm4-02', 'm4-03', 'm4-04', 'm4-05', 'm4-06',
      'm4-07', 'm4-08', 'm4-09', 'm4-10', 'm4-11',
    ],
  },
  {
    level: '入门' as const,
    week: 6,
    title: '定价与利润',
    lessons: [
      'm5-01-profit-chain', 'm5-02-vat-commission', 'm5-03-atomic-pricing',
      'm5-04-coupon-deal', 'm5-05-profit-practice',
    ],
  },
  {
    level: '入门' as const,
    week: 7,
    title: '日常运营与判断力',
    lessons: [
      'm6-01-daily-routine', 'm6-02-priority', 'm6-03-data-trust',
      'm6-04-decision-review', 'm6-05-common-mistakes', 'm6-06-hijack-buybox',
      'm6-07-returns-exceptions',
    ],
  },
  // ===== 初级（管理员内测中）=====
  {
    level: '初级' as const,
    week: 1,
    title: '广告优化实战',
    lessons: [
      'b1-01', 'b1-02', 'b1-03', 'b1-04', 'b1-05', 'b1-06',
    ],
  },
  {
    level: '初级' as const,
    week: 2,
    title: 'Listing持续优化',
    lessons: [
      'b2-01', 'b2-02', 'b2-03', 'b2-04', 'b2-05', 'b2-06',
    ],
  },
  {
    level: '初级' as const,
    week: 3,
    title: '库存精细化运营',
    lessons: [
      'b3-01', 'b3-02', 'b3-03', 'b3-04',
    ],
  },
  {
    level: '初级' as const,
    week: 4,
    title: '定价与促销策略',
    lessons: [
      'b4-01', 'b4-02', 'b4-03', 'b4-04', 'b4-05',
    ],
  },
  // ===== 中级（管理员内测中）=====
  {
    level: '中级' as const,
    week: 1,
    title: '新品冷启动全流程',
    lessons: [
      'i1-01', 'i1-02', 'i1-03', 'i1-04', 'i1-05', 'i1-06', 'i1-07',
    ],
  },
  {
    level: '中级' as const,
    week: 2,
    title: '多SKU与产品线管理',
    lessons: [
      'i2-01', 'i2-02', 'i2-03', 'i2-04', 'i2-05',
    ],
  },
  {
    level: '中级' as const,
    week: 3,
    title: '品牌化基础',
    lessons: [
      'i3-01', 'i3-02', 'i3-03', 'i3-04', 'i3-05',
    ],
  },
  {
    level: '中级' as const,
    week: 4,
    title: '数据分析与运营看板',
    lessons: [
      'i4-01', 'i4-02', 'i4-03', 'i4-04',
    ],
  },
  // ===== 高级（管理员内测中）=====
  {
    level: '高级' as const,
    week: 1,
    title: '品牌保护与长期主义',
    lessons: [
      'a1-01', 'a1-02', 'a1-03', 'a1-04', 'a1-05',
    ],
  },
  {
    level: '高级' as const,
    week: 2,
    title: '多站点全球扩张',
    lessons: [
      'a2-01', 'a2-02', 'a2-03', 'a2-04', 'a2-05', 'a2-06',
    ],
  },
  {
    level: '高级' as const,
    week: 3,
    title: '合规深水区与申诉',
    lessons: [
      'a3-01', 'a3-02', 'a3-03', 'a3-04', 'a3-05',
    ],
  },
  {
    level: '高级' as const,
    week: 4,
    title: '高阶广告与流量组合',
    lessons: [
      'a4-01', 'a4-02', 'a4-03', 'a4-04',
    ],
  },
  // ===== 进阶（管理员内测中）=====
  {
    level: '进阶' as const,
    week: 1,
    title: '团队运营与SOP',
    lessons: [
      'e1-01', 'e1-02', 'e1-03', 'e1-04', 'e1-05',
    ],
  },
  {
    level: '进阶' as const,
    week: 2,
    title: '财务与现金流管理',
    lessons: [
      'e2-01', 'e2-02', 'e2-03', 'e2-04', 'e2-05',
    ],
  },
  {
    level: '进阶' as const,
    week: 3,
    title: '战略选品与品类布局',
    lessons: [
      'e3-01', 'e3-02', 'e3-03', 'e3-04', 'e3-05',
    ],
  },
  {
    level: '进阶' as const,
    week: 4,
    title: '风险管理与危机应对',
    lessons: [
      'e4-01', 'e4-02', 'e4-03', 'e4-04', 'e4-05',
    ],
  },
]

// 所有课程（含受保护等级）
export const allLessons = curriculum.flatMap(w => w.lessons)

// 仅对公众开放的课程（普通学员可见的进度分母，不含受保护等级）
export const publicLessons = curriculum
  .filter(w => w.level === '入门')
  .flatMap(w => w.lessons)

// totalLessons 用于进度分母：保持为入门课数量，避免普通学员看到分母变大
export const totalLessons = publicLessons.length

// URL 路径 → lessonId 的权威映射表
// lessonId 命名规则在模块间不统一（m1-m4 用纯课号 m4-04，m5-m7 带完整文件名），
// 无法靠字符串推导，只能用显式映射。由构建脚本扫描各 .md 的 lessonId 生成。
// 键格式："模块目录/文件名"  如 "m4-ads/04-be-acos"
export const pathToLessonId: Record<string, string> = {
  'm1-platform/00-amazon-basics': 'm1-00',
  'm1-platform/01-what-is-ops': 'm1-01-what-is-ops',
  'm1-platform/02-account-health': 'm1-02-account-health',
  'm1-platform/03-violation-notice': 'm1-03-violation-notice',
  'm1-platform/04-listing-compliance': 'm1-04-listing-compliance',
  'm1-platform/05-review-compliance': 'm1-05-review-compliance',
  'm1-platform/06-buyer-messages': 'm1-06-buyer-messages',
  'm1-platform/07-eu-compliance': 'm1-07-eu-compliance',
  'm7-product/01-why-selection-matters': 'm7-01-why-selection-matters',
  'm7-product/02-demand-analysis': 'm7-02-demand-analysis',
  'm7-product/03-competition-analysis': 'm7-03-competition-analysis',
  'm7-product/04-profit-screening': 'm7-04-profit-screening',
  'm7-product/05-sourcing': 'm7-05-sourcing',
  'm7-product/06-selection-practice': 'm7-06-selection-practice',
  'm2-listing/00-how-to-list': 'm2-00',
  'm2-listing/01-a9-algorithm': 'm2-01',
  'm2-listing/02-title': 'm2-02',
  'm2-listing/03-bullets': 'm2-03',
  'm2-listing/03b-description': 'm2-03b',
  'm2-listing/04-search-terms': 'm2-04',
  'm2-listing/05-images': 'm2-05',
  'm2-listing/06-category-attributes': 'm2-06',
  'm2-listing/07-keyword-research': 'm2-07',
  'm2-listing/08-listing-practice': 'm2-08',
  'm2-listing/09-brand-a-plus': 'm2-09',
  'm2-listing/10-competitor-research': 'm2-10',
  'm3-inventory/01-fba-basics': 'm3-01',
  'm3-inventory/02-fba-fees': 'm3-02',
  'm3-inventory/03-turnover-days': 'm3-03',
  'm3-inventory/04-replenishment': 'm3-04',
  'm3-inventory/05-shipment-status': 'm3-05',
  'm3-inventory/06-stockout-prevention': 'm3-06',
  'm3-inventory/07-shipping-practice': 'm3-07',
  'm4-ads/01-ad-types': 'm4-01',
  'm4-ads/02-match-types': 'm4-02',
  'm4-ads/03-metrics': 'm4-03',
  'm4-ads/04-be-acos': 'm4-04',
  'm4-ads/05-campaign-structure': 'm4-05',
  'm4-ads/06-graduation-negative': 'm4-06',
  'm4-ads/07-bidding': 'm4-07',
  'm4-ads/08-reports': 'm4-08',
  'm4-ads/09-new-product-strategy': 'm4-09',
  'm4-ads/10-ads-practice': 'm4-10',
  'm4-ads/11-vine-reviews': 'm4-11',
  'm5-pricing/01-profit-chain': 'm5-01-profit-chain',
  'm5-pricing/02-vat-commission': 'm5-02-vat-commission',
  'm5-pricing/03-atomic-pricing': 'm5-03-atomic-pricing',
  'm5-pricing/04-coupon-deal': 'm5-04-coupon-deal',
  'm5-pricing/05-profit-practice': 'm5-05-profit-practice',
  'm6-daily/01-daily-routine': 'm6-01-daily-routine',
  'm6-daily/02-priority': 'm6-02-priority',
  'm6-daily/03-data-trust': 'm6-03-data-trust',
  'm6-daily/04-decision-review': 'm6-04-decision-review',
  'm6-daily/05-common-mistakes': 'm6-05-common-mistakes',
  'm6-daily/06-hijack-buybox': 'm6-06-hijack-buybox',
  'm6-daily/07-returns-exceptions': 'm6-07-returns-exceptions',
  // ===== 初级课程（管理员内测中）=====
  'b1-ads-optimization/01-search-term-attribution': 'b1-01',
  'b1-ads-optimization/02-negative-keyword-pool': 'b1-02',
  'b1-ads-optimization/03-dayparting-tos': 'b1-03',
  'b1-ads-optimization/04-acos-reduction-loop': 'b1-04',
  'b1-ads-optimization/05-weekly-checklist-practice': 'b1-05',
  'b1-ads-optimization/06-sb-sd-ads': 'b1-06',
  'b2-listing-optimization/01-ab-testing': 'b2-01',
  'b2-listing-optimization/02-rank-monitoring': 'b2-02',
  'b2-listing-optimization/03-search-terms-iteration': 'b2-03',
  'b2-listing-optimization/04-image-ctr': 'b2-04',
  'b2-listing-optimization/05-listing-audit-practice': 'b2-05',
  'b2-listing-optimization/06-review-management': 'b2-06',
  'b3-inventory-advanced/01-replenishment-model': 'b3-01',
  'b3-inventory-advanced/02-stock-budget': 'b3-02',
  'b3-inventory-advanced/03-stagnant-inventory': 'b3-03',
  'b3-inventory-advanced/04-replenishment-practice': 'b3-04',
  'b4-pricing-strategy/01-competitor-pricing': 'b4-01',
  'b4-pricing-strategy/02-promo-rhythm': 'b4-02',
  'b4-pricing-strategy/03-price-elasticity': 'b4-03',
  'b4-pricing-strategy/04-monthly-promo-plan': 'b4-04',
  'b4-pricing-strategy/05-buybox-hijack-defense': 'b4-05',
  // ===== 中级课程 =====
  'i1-cold-start/01-selection-validation': 'i1-01',
  'i1-cold-start/02-launch-timeline': 'i1-02',
  'i1-cold-start/03-cold-start-four-phases': 'i1-03',
  'i1-cold-start/04-ranking-push': 'i1-04',
  'i1-cold-start/05-first-reviews': 'i1-05',
  'i1-cold-start/06-traffic-structure': 'i1-06',
  'i1-cold-start/07-launch-plan-practice': 'i1-07',
  'i2-multi-sku/01-product-line-planning': 'i2-01',
  'i2-multi-sku/02-new-old-ratio': 'i2-02',
  'i2-multi-sku/03-sku-rationalization': 'i2-03',
  'i2-multi-sku/04-lifecycle-management': 'i2-04',
  'i2-multi-sku/05-portfolio-review-practice': 'i2-05',
  'i3-branding/01-brand-registry-deep': 'i3-01',
  'i3-branding/02-a-plus-premium': 'i3-02',
  'i3-branding/03-brand-store': 'i3-03',
  'i3-branding/04-brand-analytics': 'i3-04',
  'i3-branding/05-brand-foundation-practice': 'i3-05',
  'i4-data-analysis/01-business-reports': 'i4-01',
  'i4-data-analysis/02-third-party-tools': 'i4-02',
  'i4-data-analysis/03-growth-diagnosis': 'i4-03',
  'i4-data-analysis/04-dashboard-building': 'i4-04',
  // ===== 高级课程 =====
  'a1-brand-protection/01-transparency-program': 'a1-01',
  'a1-brand-protection/02-project-zero': 'a1-02',
  'a1-brand-protection/03-hijack-defense-sop': 'a1-03',
  'a1-brand-protection/04-brand-assets': 'a1-04',
  'a1-brand-protection/05-defense-strategy-practice': 'a1-05',
  'a2-global-expansion/01-site-differences': 'a2-01',
  'a2-global-expansion/02-fba-vs-fbm-choice': 'a2-02',
  'a2-global-expansion/03-cross-border-logistics': 'a2-03',
  'a2-global-expansion/04-localization': 'a2-04',
  'a2-global-expansion/05-tax-compliance': 'a2-05',
  'a2-global-expansion/06-expansion-feasibility-practice': 'a2-06',
  'a3-compliance-appeal/01-account-suspension-appeal': 'a3-01',
  'a3-compliance-appeal/02-infringement': 'a3-02',
  'a3-compliance-appeal/03-video-verification': 'a3-03',
  'a3-compliance-appeal/04-review-manipulation': 'a3-04',
  'a3-compliance-appeal/05-appeal-writing-practice': 'a3-05',
  'a4-advanced-ads/01-dsp-ads': 'a4-01',
  'a4-advanced-ads/02-sd-retargeting': 'a4-02',
  'a4-advanced-ads/03-brand-ads-combo': 'a4-03',
  'a4-advanced-ads/04-full-funnel-strategy': 'a4-04',
  // ===== 进阶课程 =====
  'e1-team-sop/01-role-design': 'e1-01',
  'e1-team-sop/02-kpi-design': 'e1-02',
  'e1-team-sop/03-sop-system': 'e1-03',
  'e1-team-sop/04-training-system': 'e1-04',
  'e1-team-sop/05-team-framework-practice': 'e1-05',
  'e2-finance-cashflow/01-capital-budget': 'e2-01',
  'e2-finance-cashflow/02-turnover-management': 'e2-02',
  'e2-finance-cashflow/03-profit-aggregation': 'e2-03',
  'e2-finance-cashflow/04-cashflow-warning': 'e2-04',
  'e2-finance-cashflow/05-financial-model-practice': 'e2-05',
  'e3-category-strategy/01-category-positioning': 'e3-01',
  'e3-category-strategy/02-product-matrix': 'e3-02',
  'e3-category-strategy/03-moat-building': 'e3-03',
  'e3-category-strategy/04-long-term-planning': 'e3-04',
  'e3-category-strategy/05-category-strategy-practice': 'e3-05',
  'e4-risk-management/01-account-risk-system': 'e4-01',
  'e4-risk-management/02-inventory-capital-risk': 'e4-02',
  'e4-risk-management/03-policy-change-response': 'e4-03',
  'e4-risk-management/04-black-swan-playbook': 'e4-04',
  'e4-risk-management/05-risk-playbook-practice': 'e4-05',
  // ===== 技能补给站 =====
  'domain-basics': 'skill-domain',
  'phishing-detection': 'skill-phishing',
  'system-shortcuts': 'skill-shortcuts',
  'browser-shortcuts': 'skill-browser',
  'excel-for-ops': 'skill-excel',
  // ===== AI 工作流（2026 新增，限免登录可见）=====
  'ai-image-workflow': 'skill-ai-image',
  'ai-listing-rufus': 'skill-ai-rufus',
  'ai-selection-keywords': 'skill-ai-keywords',
  'ai-ads-ops': 'skill-ai-ops',
  // ===== 实战手册（playbooks，独立栏目，仅管理员可见）=====
  // 不进入 curriculum 主数组、不参与 publicLessons/totalLessons 统计
  'ads-16-tactics/index': 'pb-ads-00',
  'ads-16-tactics/01-low-budget-bargain': 'pb-ads-01',
  'ads-16-tactics/02-asin-targeting': 'pb-ads-02',
  'ads-16-tactics/03-auto-ads-refinement': 'pb-ads-03',
  'ads-16-tactics/04-ranking-push-and-risk': 'pb-ads-04',
  'ads-16-tactics/05-peak-season-combo': 'pb-ads-05',
}

// ===== 技能补给站：独立栏目（登录可见，不参与五级体系）=====
// 仅用于 ContinueCard 等按 lessonId 反查标题的场景。
// 刻意不进入 curriculum 主数组，以免污染进度统计（publicLessons/totalLessons）
// 与管理员看板；其访问门控走 accessControl 里的 isSkillPath 那一套，与等级无关。
export const skillLessons: { lessonId: string; title: string }[] = [
  { lessonId: 'skill-domain', title: '域名结构与网址识别' },
  { lessonId: 'skill-phishing', title: '钓鱼网站识别' },
  { lessonId: 'skill-shortcuts', title: '电脑快捷键基础（Windows + Mac）' },
  { lessonId: 'skill-browser', title: '浏览器快捷键实战' },
  { lessonId: 'skill-excel', title: 'Excel 三大神器（运营向）' },
  // ===== AI 工作流（2026 新增，限免登录可见）=====
  { lessonId: 'skill-ai-image', title: 'AI 生图工作流（亚马逊合规版）' },
  { lessonId: 'skill-ai-rufus', title: 'AI 文案与 Rufus 问答覆盖' },
  { lessonId: 'skill-ai-keywords', title: 'AI 选品与关键词反查' },
  { lessonId: 'skill-ai-ops', title: 'AI 广告与运营提效' },
]

// ===== 实战手册（playbooks）：独立栏目（仅管理员可见，不参与五级体系）=====
// 仅用于 ContinueCard 等按 lessonId 反查标题的场景。
// 刻意不进入 curriculum 主数组，以免污染进度统计（publicLessons/totalLessons）
// 与管理员看板；其访问门控走 accessControl 里的 isPlaybookPath 那一套，与等级无关。
export const playbookLessons: { lessonId: string; title: string }[] = [
  { lessonId: 'pb-ads-00', title: '广告打法手册 · 首页' },
  { lessonId: 'pb-ads-01', title: '第1节 · 小预算捡漏组合' },
  { lessonId: 'pb-ads-02', title: '第2节 · ASIN 定位与流量卡位' },
  { lessonId: 'pb-ads-03', title: '第3节 · 自动广告精细化' },
  { lessonId: 'pb-ads-04', title: '第4节 · 关键词排名冲刺与风险教育' },
  { lessonId: 'pb-ads-05', title: '第5节 · 旺季与综合打法' },
]

// 课程内容的目录前缀（getLessonIdByPath 用）
const CONTENT_PREFIXES = [
  'content/modules/',
  'content/beginner/',
  'content/intermediate/',
  'content/advanced/',
  'content/expert/',
  'content/skills/',
  'content/playbooks/',
]

// 根据页面相对路径推导 lessonId（Comments 组件零侵入注入用）
export function getLessonIdByPath(relativePath: string): string | null {
  if (!relativePath) return null
  // 尝试匹配已知的内容目录前缀
  for (const prefix of CONTENT_PREFIXES) {
    if (relativePath.startsWith(prefix)) {
      const key = relativePath
        .replace(prefix, '')
        .replace(/\.md$/, '')
      const id = pathToLessonId[key]
      if (id) return id
    }
  }
  return null
}

// URL 路径 → lessonId（与 getLessonIdByPath 同逻辑，但吃的是浏览器 URL）
// 评论管理 / 访问分析等后台页面用 URL 反查课名时调用
export function getLessonIdByUrl(url: string): string | null {
  if (!url) return null
  for (const prefix of CONTENT_PREFIXES) {
    const urlPrefix = '/' + prefix // content/modules/ → /content/modules/
    if (url.startsWith(urlPrefix)) {
      const key = url.slice(urlPrefix.length).replace(/\.html$/, '')
      const id = pathToLessonId[key]
      if (id) return id
    }
  }
  return null
}

// lessonId → 课程页 URL（从生成器产出的 lessonIdToUrl 反查）
// 用于后台点击课程名跳转。取不到返回 null。
export function getLessonUrl(id: string): string | null {
  return lessonIdToUrl[id] || null
}

// ===== 以下由 scripts/gen-lesson-titles.mjs 自动生成，请勿手改 =====
// lessonId → 真实课名（从各 .md 的 title: frontmatter 扫描得来）
// 重新生成：node scripts/gen-lesson-titles.mjs
export const lessonTitles: Record<string, string> = {
  'a1-01': "Transparency 透明计划",
  'a1-02': "Project Zero 与自动保护",
  'a1-03': "跟卖打击 SOP",
  'a1-04': "品牌资产沉淀",
  'a1-05': "品牌防御体系搭建（实操）",
  'a2-01': "美欧日站点差异",
  'a2-02': "自发货 vs FBA 选择",
  'a2-03': "跨境物流方案",
  'a2-04': "Listing 本地化",
  'a2-05': "各国税务合规",
  'a2-06': "新站点扩张可行性评估（实操）",
  'a3-01': "账号冻结申诉全流程",
  'a3-02': "侵权处理",
  'a3-03': "视频验证应对",
  'a3-04': "评论违规与恢复",
  'a3-05': "撰写一份 POA 申诉书（实操）",
  'a4-01': "DSP 广告入门",
  'a4-02': "SD 再营销",
  'a4-03': "品牌广告组合",
  'a4-04': "全漏斗流量打法设计（实操）",
  'b1-01': "搜索词报表与归因窗口",
  'b1-02': "否定词池搭建",
  'b1-03': "分时调价与 TOS 抢占",
  'b1-04': "ACOS 压降闭环",
  'b1-05': "周度优化清单（实操）",
  'b1-06': "品牌广告与展示广告（SB/SD）",
  'b2-01': "文案A/B测试（Manage Your Experiments）",
  'b2-02': "关键词排名监控",
  'b2-03': "Search Terms 持续迭代",
  'b2-04': "图片点击率优化",
  'b2-05': "Listing 体检（实操）",
  'b2-06': "评论获取与差评管理",
  'b3-01': "补货量计算模型",
  'b3-02': "备货资金预算",
  'b3-03': "滞销预警与处理",
  'b3-04': "补货计划（实操）",
  'b4-01': "竞品定价跟踪",
  'b4-02': "促销节奏设计",
  'b4-03': "价格弹性测试",
  'b4-04': "月度促销表（实操）",
  'b4-05': "Buy Box 防御与跟卖应对",
  'e1-01': "运营岗位分工与职责边界",
  'e1-02': "KPI设计：利润导向 vs 销量导向",
  'e1-03': "SOP化与流程沉淀：哪些该SOP，哪些不该",
  'e1-04': "新人培训体系：30/60/90 天培养计划",
  'e1-05': "团队管理框架实操：岗位+KPI+SOP",
  'e2-01': "资金预算与占用：多 SKU 总资金盘规划",
  'e2-02': "库存周转天数管理：全盘、单品、资金三层",
  'e2-03': "利润盘汇总：把真实利润算准",
  'e2-04': "现金流预警：断裂信号、安全水位、应急预案",
  'e2-05': "财务监控表实操：利润+现金流一张表",
  'e3-01': "品类卡位分析：找位置、避红海、挖缝隙",
  'e3-02': "产品矩阵设计：引流/利润/形象/防御的战略配比",
  'e3-03': "护城河构建：产品/供应链/品牌/数据四维壁垒",
  'e3-04': "长期品类规划：1年/3年路线图",
  'e3-05': "品类战略规划实操：一份能用的总纲",
  'e4-01': "账号风险预警体系：健康度监控与分级",
  'e4-02': "库存与资金风险：滞销/断货/汇率的风险量化与对冲",
  'e4-03': "平台政策变动应对：解读、评估、调整节奏",
  'e4-04': "黑天鹅预案：封号/断供/物流中断的应急模板",
  'e4-05': "风险预警与应急预案实操：一套总纲",
  'i1-01': "选款验证（数据化测款）",
  'i1-02': "上架节奏规划（0-60 天作战日历）",
  'i1-03': "冷启动四阶段细化（种子/成长/冲刺/稳定）",
  'i1-04': "榜单冲刺打法（BSR 卡位与关键词上首页）",
  'i1-05': "首批评论策略（Vine 深度用法与差评预防）",
  'i1-06': "流量结构搭建（自然+广告+关联）",
  'i1-07': "新品 0-60 天作战计划（实操）",
  'i2-01': "产品线规划（引流/利润/形象款矩阵）",
  'i2-02': "新老品配比与资源分配",
  'i2-03': "SKU 精简与聚焦（砍掉哪些、为什么、何时砍）",
  'i2-04': "产品生命周期管理（导入/成长/成熟/衰退）",
  'i2-05': "产品线健康度盘点（实操）",
  'i3-01': "品牌备案深度用法",
  'i3-02': "A+ 高级版与品牌故事",
  'i3-03': "品牌旗舰店搭建",
  'i3-04': "Brand Analytics 实战",
  'i3-05': "品牌基础搭建清单（实操）",
  'i4-01': "Business Reports 深读",
  'i4-02': "第三方工具实战（Helium10/Jungle Scout/Sorftime）",
  'i4-03': "用数据找增长点",
  'i4-04': "自建运营看板",
  'm1-00': "亚马逊基础知识和专业术语",
  'm1-01-what-is-ops': "运营到底是什么工作",
  'm1-02-account-health': "账号健康4指标",
  'm1-03-violation-notice': "收到违规通知怎么办",
  'm1-04-listing-compliance': "Listing合规红线",
  'm1-05-review-compliance': "评论合规",
  'm1-06-buyer-messages': "买家消息边界",
  'm1-07-eu-compliance': "EU合规基础",
  'm2-00': "如何上架产品",
  'm2-01': "搜索算法全景：A9 + COSMO + AI 助手",
  'm2-02': "标题怎么写",
  'm2-03': "五点描述怎么写",
  'm2-03b': "长描述怎么写",
  'm2-04': "Search Terms",
  'm2-05': "主图与副图体系",
  'm2-06': "类目与后台属性",
  'm2-07': "关键词研究方法",
  'm2-08': "Listing实操",
  'm2-09': "品牌备案与A+内容",
  'm2-10': "竞品研究方法",
  'm3-01': "FBA基本逻辑",
  'm3-02': "FBA费用体系",
  'm3-03': "库存周转与可售天数",
  'm3-04': "补货逻辑",
  'm3-05': "货件状态分类",
  'm3-06': "断货预防",
  'm3-07': "发货计划实操",
  'm4-01': "广告类型与基础",
  'm4-02': "关键词匹配类型",
  'm4-03': "核心指标",
  'm4-04': "BE ACOS",
  'm4-05': "广告结构设计",
  'm4-06': "关键词毕业与否定",
  'm4-07': "出价调整逻辑",
  'm4-08': "广告报表解读",
  'm4-09': "新品广告策略",
  'm4-10': "广告实操",
  'm4-11': "评论获取与Amazon Vine",
  'm5-01-profit-chain': "利润链全貌",
  'm5-02-vat-commission': "VAT与佣金基数",
  'm5-03-atomic-pricing': "调价是原子操作",
  'm5-04-coupon-deal': "Coupon与Deal",
  'm5-05-profit-practice': "利润手算实操",
  'm6-01-daily-routine': "每日工作流程",
  'm6-02-priority': "优先级判断",
  'm6-03-data-trust': "数据可信度检查",
  'm6-04-decision-review': "决策记录与复盘",
  'm6-05-common-mistakes': "常见误判",
  'm6-06-hijack-buybox': "跟卖防御与Buy Box",
  'm6-07-returns-exceptions': "退货退款与异常处理",
  'm7-01-why-selection-matters': "选品决定80%的成败",
  'm7-02-demand-analysis': "市场需求分析",
  'm7-03-competition-analysis': "竞争强度评估",
  'm7-04-profit-screening': "利润预筛",
  'm7-05-sourcing': "找供应商与采购",
  'm7-06-selection-practice': "选品实操",
  'pb-ads-00': "广告打法手册 · 16 种实战打法合集",
  'pb-ads-01': "第1节 · 小预算捡漏组合（乞丐/错词/西语/品牌）",
  'pb-ads-02': "第2节 · ASIN 定位与流量卡位（定位四组/类目/霸屏）",
  'pb-ads-03': "第3节 · 自动广告精细化（四组拆分/阶梯竞价/标签/关键词调研）",
  'pb-ads-04': "第4节 · 关键词排名冲刺与风险教育（⚠️含违规打法）",
  'pb-ads-05': "第5节 · 旺季与综合打法（流量七分/海王/竞品投放）",
  'skill-ai-image': "AI 生图工作流（亚马逊合规版）",
  'skill-ai-keywords': "AI 选品与关键词反查",
  'skill-ai-ops': "AI 广告与运营提效",
  'skill-ai-rufus': "AI 文案与 Rufus 问答覆盖",
  'skill-browser': "浏览器快捷键实战",
  'skill-domain': "域名结构与网址识别",
  'skill-excel': "Excel 三大神器（运营向）",
  'skill-phishing': "钓鱼网站识别",
  'skill-shortcuts': "电脑快捷键基础（Windows + Mac）",
}

// lessonId → 课序号（如 'm4-04' → '5.4'），用于后台展示
export const lessonNumbers: Record<string, string> = {
  'a1-01': '1.1',
  'a1-02': '1.2',
  'a1-03': '1.3',
  'a1-04': '1.4',
  'a1-05': '1.5',
  'a2-01': '2.1',
  'a2-02': '2.2',
  'a2-03': '2.3',
  'a2-04': '2.4',
  'a2-05': '2.5',
  'a2-06': '2.6',
  'a3-01': '3.1',
  'a3-02': '3.2',
  'a3-03': '3.3',
  'a3-04': '3.4',
  'a3-05': '3.5',
  'a4-01': '4.1',
  'a4-02': '4.2',
  'a4-03': '4.3',
  'a4-04': '4.4',
  'b1-01': '1.1',
  'b1-02': '1.2',
  'b1-03': '1.3',
  'b1-04': '1.4',
  'b1-05': '1.5',
  'b1-06': '1.6',
  'b2-01': '2.1',
  'b2-02': '2.2',
  'b2-03': '2.3',
  'b2-04': '2.4',
  'b2-05': '2.5',
  'b2-06': '2.6',
  'b3-01': '3.1',
  'b3-02': '3.2',
  'b3-03': '3.3',
  'b3-04': '3.4',
  'b4-01': '4.1',
  'b4-02': '4.2',
  'b4-03': '4.3',
  'b4-04': '4.4',
  'b4-05': '4.5',
  'e1-01': '1.1',
  'e1-02': '1.2',
  'e1-03': '1.3',
  'e1-04': '1.4',
  'e1-05': '1.5',
  'e2-01': '2.1',
  'e2-02': '2.2',
  'e2-03': '2.3',
  'e2-04': '2.4',
  'e2-05': '2.5',
  'e3-01': '3.1',
  'e3-02': '3.2',
  'e3-03': '3.3',
  'e3-04': '3.4',
  'e3-05': '3.5',
  'e4-01': '4.1',
  'e4-02': '4.2',
  'e4-03': '4.3',
  'e4-04': '4.4',
  'e4-05': '4.5',
  'i1-01': '1.1',
  'i1-02': '1.2',
  'i1-03': '1.3',
  'i1-04': '1.4',
  'i1-05': '1.5',
  'i1-06': '1.6',
  'i1-07': '1.7',
  'i2-01': '2.1',
  'i2-02': '2.2',
  'i2-03': '2.3',
  'i2-04': '2.4',
  'i2-05': '2.5',
  'i3-01': '3.1',
  'i3-02': '3.2',
  'i3-03': '3.3',
  'i3-04': '3.4',
  'i3-05': '3.5',
  'i4-01': '4.1',
  'i4-02': '4.2',
  'i4-03': '4.3',
  'i4-04': '4.4',
  'm1-00': '1.0',
  'm1-01-what-is-ops': '1.1',
  'm1-02-account-health': '1.2',
  'm1-03-violation-notice': '1.3',
  'm1-04-listing-compliance': '1.4',
  'm1-05-review-compliance': '1.5',
  'm1-06-buyer-messages': '1.6',
  'm1-07-eu-compliance': '1.7',
  'm2-00': '3.0',
  'm2-01': '3.1',
  'm2-02': '3.2',
  'm2-03': '3.3',
  'm2-03b': '3.3b',
  'm2-04': '3.4',
  'm2-05': '3.5',
  'm2-06': '3.6',
  'm2-07': '3.7',
  'm2-08': '3.8',
  'm2-09': '3.9',
  'm2-10': '3.10',
  'm3-01': '4.1',
  'm3-02': '4.2',
  'm3-03': '4.3',
  'm3-04': '4.4',
  'm3-05': '4.5',
  'm3-06': '4.6',
  'm3-07': '4.7',
  'm4-01': '5.1',
  'm4-02': '5.2',
  'm4-03': '5.3',
  'm4-04': '5.4',
  'm4-05': '5.5',
  'm4-06': '5.6',
  'm4-07': '5.7',
  'm4-08': '5.8',
  'm4-09': '5.9',
  'm4-10': '5.10',
  'm4-11': '5.11',
  'm5-01-profit-chain': '6.1',
  'm5-02-vat-commission': '6.2',
  'm5-03-atomic-pricing': '6.3',
  'm5-04-coupon-deal': '6.4',
  'm5-05-profit-practice': '6.5',
  'm6-01-daily-routine': '7.1',
  'm6-02-priority': '7.2',
  'm6-03-data-trust': '7.3',
  'm6-04-decision-review': '7.4',
  'm6-05-common-mistakes': '7.5',
  'm6-06-hijack-buybox': '7.6',
  'm6-07-returns-exceptions': '7.7',
  'm7-01-why-selection-matters': '2.1',
  'm7-02-demand-analysis': '2.2',
  'm7-03-competition-analysis': '2.3',
  'm7-04-profit-screening': '2.4',
  'm7-05-sourcing': '2.5',
  'm7-06-selection-practice': '2.6',
  'pb-ads-00': '手册1',
  'pb-ads-01': '手册2',
  'pb-ads-02': '手册3',
  'pb-ads-03': '手册4',
  'pb-ads-04': '手册5',
  'pb-ads-05': '手册6',
  'skill-ai-image': '技能6',
  'skill-ai-keywords': '技能8',
  'skill-ai-ops': '技能9',
  'skill-ai-rufus': '技能7',
  'skill-browser': '技能4',
  'skill-domain': '技能1',
  'skill-excel': '技能5',
  'skill-phishing': '技能2',
  'skill-shortcuts': '技能3',
}

// lessonId → 课程页 URL（如 'm4-04' → '/content/modules/m4-ads/04-be-acos'）
// 用于后台点击课程名跳转到对应课程页
export const lessonIdToUrl: Record<string, string> = {
  'a1-01': '/content/advanced/a1-brand-protection/01-transparency-program',
  'a1-02': '/content/advanced/a1-brand-protection/02-project-zero',
  'a1-03': '/content/advanced/a1-brand-protection/03-hijack-defense-sop',
  'a1-04': '/content/advanced/a1-brand-protection/04-brand-assets',
  'a1-05': '/content/advanced/a1-brand-protection/05-defense-strategy-practice',
  'a2-01': '/content/advanced/a2-global-expansion/01-site-differences',
  'a2-02': '/content/advanced/a2-global-expansion/02-fba-vs-fbm-choice',
  'a2-03': '/content/advanced/a2-global-expansion/03-cross-border-logistics',
  'a2-04': '/content/advanced/a2-global-expansion/04-localization',
  'a2-05': '/content/advanced/a2-global-expansion/05-tax-compliance',
  'a2-06': '/content/advanced/a2-global-expansion/06-expansion-feasibility-practice',
  'a3-01': '/content/advanced/a3-compliance-appeal/01-account-suspension-appeal',
  'a3-02': '/content/advanced/a3-compliance-appeal/02-infringement',
  'a3-03': '/content/advanced/a3-compliance-appeal/03-video-verification',
  'a3-04': '/content/advanced/a3-compliance-appeal/04-review-manipulation',
  'a3-05': '/content/advanced/a3-compliance-appeal/05-appeal-writing-practice',
  'a4-01': '/content/advanced/a4-advanced-ads/01-dsp-ads',
  'a4-02': '/content/advanced/a4-advanced-ads/02-sd-retargeting',
  'a4-03': '/content/advanced/a4-advanced-ads/03-brand-ads-combo',
  'a4-04': '/content/advanced/a4-advanced-ads/04-full-funnel-strategy',
  'b1-01': '/content/beginner/b1-ads-optimization/01-search-term-attribution',
  'b1-02': '/content/beginner/b1-ads-optimization/02-negative-keyword-pool',
  'b1-03': '/content/beginner/b1-ads-optimization/03-dayparting-tos',
  'b1-04': '/content/beginner/b1-ads-optimization/04-acos-reduction-loop',
  'b1-05': '/content/beginner/b1-ads-optimization/05-weekly-checklist-practice',
  'b1-06': '/content/beginner/b1-ads-optimization/06-sb-sd-ads',
  'b2-01': '/content/beginner/b2-listing-optimization/01-ab-testing',
  'b2-02': '/content/beginner/b2-listing-optimization/02-rank-monitoring',
  'b2-03': '/content/beginner/b2-listing-optimization/03-search-terms-iteration',
  'b2-04': '/content/beginner/b2-listing-optimization/04-image-ctr',
  'b2-05': '/content/beginner/b2-listing-optimization/05-listing-audit-practice',
  'b2-06': '/content/beginner/b2-listing-optimization/06-review-management',
  'b3-01': '/content/beginner/b3-inventory-advanced/01-replenishment-model',
  'b3-02': '/content/beginner/b3-inventory-advanced/02-stock-budget',
  'b3-03': '/content/beginner/b3-inventory-advanced/03-stagnant-inventory',
  'b3-04': '/content/beginner/b3-inventory-advanced/04-replenishment-practice',
  'b4-01': '/content/beginner/b4-pricing-strategy/01-competitor-pricing',
  'b4-02': '/content/beginner/b4-pricing-strategy/02-promo-rhythm',
  'b4-03': '/content/beginner/b4-pricing-strategy/03-price-elasticity',
  'b4-04': '/content/beginner/b4-pricing-strategy/04-monthly-promo-plan',
  'b4-05': '/content/beginner/b4-pricing-strategy/05-buybox-hijack-defense',
  'e1-01': '/content/expert/e1-team-sop/01-role-design',
  'e1-02': '/content/expert/e1-team-sop/02-kpi-design',
  'e1-03': '/content/expert/e1-team-sop/03-sop-system',
  'e1-04': '/content/expert/e1-team-sop/04-training-system',
  'e1-05': '/content/expert/e1-team-sop/05-team-framework-practice',
  'e2-01': '/content/expert/e2-finance-cashflow/01-capital-budget',
  'e2-02': '/content/expert/e2-finance-cashflow/02-turnover-management',
  'e2-03': '/content/expert/e2-finance-cashflow/03-profit-aggregation',
  'e2-04': '/content/expert/e2-finance-cashflow/04-cashflow-warning',
  'e2-05': '/content/expert/e2-finance-cashflow/05-financial-model-practice',
  'e3-01': '/content/expert/e3-category-strategy/01-category-positioning',
  'e3-02': '/content/expert/e3-category-strategy/02-product-matrix',
  'e3-03': '/content/expert/e3-category-strategy/03-moat-building',
  'e3-04': '/content/expert/e3-category-strategy/04-long-term-planning',
  'e3-05': '/content/expert/e3-category-strategy/05-category-strategy-practice',
  'e4-01': '/content/expert/e4-risk-management/01-account-risk-system',
  'e4-02': '/content/expert/e4-risk-management/02-inventory-capital-risk',
  'e4-03': '/content/expert/e4-risk-management/03-policy-change-response',
  'e4-04': '/content/expert/e4-risk-management/04-black-swan-playbook',
  'e4-05': '/content/expert/e4-risk-management/05-risk-playbook-practice',
  'i1-01': '/content/intermediate/i1-cold-start/01-selection-validation',
  'i1-02': '/content/intermediate/i1-cold-start/02-launch-timeline',
  'i1-03': '/content/intermediate/i1-cold-start/03-cold-start-four-phases',
  'i1-04': '/content/intermediate/i1-cold-start/04-ranking-push',
  'i1-05': '/content/intermediate/i1-cold-start/05-first-reviews',
  'i1-06': '/content/intermediate/i1-cold-start/06-traffic-structure',
  'i1-07': '/content/intermediate/i1-cold-start/07-launch-plan-practice',
  'i2-01': '/content/intermediate/i2-multi-sku/01-product-line-planning',
  'i2-02': '/content/intermediate/i2-multi-sku/02-new-old-ratio',
  'i2-03': '/content/intermediate/i2-multi-sku/03-sku-rationalization',
  'i2-04': '/content/intermediate/i2-multi-sku/04-lifecycle-management',
  'i2-05': '/content/intermediate/i2-multi-sku/05-portfolio-review-practice',
  'i3-01': '/content/intermediate/i3-branding/01-brand-registry-deep',
  'i3-02': '/content/intermediate/i3-branding/02-a-plus-premium',
  'i3-03': '/content/intermediate/i3-branding/03-brand-store',
  'i3-04': '/content/intermediate/i3-branding/04-brand-analytics',
  'i3-05': '/content/intermediate/i3-branding/05-brand-foundation-practice',
  'i4-01': '/content/intermediate/i4-data-analysis/01-business-reports',
  'i4-02': '/content/intermediate/i4-data-analysis/02-third-party-tools',
  'i4-03': '/content/intermediate/i4-data-analysis/03-growth-diagnosis',
  'i4-04': '/content/intermediate/i4-data-analysis/04-dashboard-building',
  'm1-00': '/content/modules/m1-platform/00-amazon-basics',
  'm1-01-what-is-ops': '/content/modules/m1-platform/01-what-is-ops',
  'm1-02-account-health': '/content/modules/m1-platform/02-account-health',
  'm1-03-violation-notice': '/content/modules/m1-platform/03-violation-notice',
  'm1-04-listing-compliance': '/content/modules/m1-platform/04-listing-compliance',
  'm1-05-review-compliance': '/content/modules/m1-platform/05-review-compliance',
  'm1-06-buyer-messages': '/content/modules/m1-platform/06-buyer-messages',
  'm1-07-eu-compliance': '/content/modules/m1-platform/07-eu-compliance',
  'm2-00': '/content/modules/m2-listing/00-how-to-list',
  'm2-01': '/content/modules/m2-listing/01-a9-algorithm',
  'm2-02': '/content/modules/m2-listing/02-title',
  'm2-03': '/content/modules/m2-listing/03-bullets',
  'm2-03b': '/content/modules/m2-listing/03b-description',
  'm2-04': '/content/modules/m2-listing/04-search-terms',
  'm2-05': '/content/modules/m2-listing/05-images',
  'm2-06': '/content/modules/m2-listing/06-category-attributes',
  'm2-07': '/content/modules/m2-listing/07-keyword-research',
  'm2-08': '/content/modules/m2-listing/08-listing-practice',
  'm2-09': '/content/modules/m2-listing/09-brand-a-plus',
  'm2-10': '/content/modules/m2-listing/10-competitor-research',
  'm3-01': '/content/modules/m3-inventory/01-fba-basics',
  'm3-02': '/content/modules/m3-inventory/02-fba-fees',
  'm3-03': '/content/modules/m3-inventory/03-turnover-days',
  'm3-04': '/content/modules/m3-inventory/04-replenishment',
  'm3-05': '/content/modules/m3-inventory/05-shipment-status',
  'm3-06': '/content/modules/m3-inventory/06-stockout-prevention',
  'm3-07': '/content/modules/m3-inventory/07-shipping-practice',
  'm4-01': '/content/modules/m4-ads/01-ad-types',
  'm4-02': '/content/modules/m4-ads/02-match-types',
  'm4-03': '/content/modules/m4-ads/03-metrics',
  'm4-04': '/content/modules/m4-ads/04-be-acos',
  'm4-05': '/content/modules/m4-ads/05-campaign-structure',
  'm4-06': '/content/modules/m4-ads/06-graduation-negative',
  'm4-07': '/content/modules/m4-ads/07-bidding',
  'm4-08': '/content/modules/m4-ads/08-reports',
  'm4-09': '/content/modules/m4-ads/09-new-product-strategy',
  'm4-10': '/content/modules/m4-ads/10-ads-practice',
  'm4-11': '/content/modules/m4-ads/11-vine-reviews',
  'm5-01-profit-chain': '/content/modules/m5-pricing/01-profit-chain',
  'm5-02-vat-commission': '/content/modules/m5-pricing/02-vat-commission',
  'm5-03-atomic-pricing': '/content/modules/m5-pricing/03-atomic-pricing',
  'm5-04-coupon-deal': '/content/modules/m5-pricing/04-coupon-deal',
  'm5-05-profit-practice': '/content/modules/m5-pricing/05-profit-practice',
  'm6-01-daily-routine': '/content/modules/m6-daily/01-daily-routine',
  'm6-02-priority': '/content/modules/m6-daily/02-priority',
  'm6-03-data-trust': '/content/modules/m6-daily/03-data-trust',
  'm6-04-decision-review': '/content/modules/m6-daily/04-decision-review',
  'm6-05-common-mistakes': '/content/modules/m6-daily/05-common-mistakes',
  'm6-06-hijack-buybox': '/content/modules/m6-daily/06-hijack-buybox',
  'm6-07-returns-exceptions': '/content/modules/m6-daily/07-returns-exceptions',
  'm7-01-why-selection-matters': '/content/modules/m7-product/01-why-selection-matters',
  'm7-02-demand-analysis': '/content/modules/m7-product/02-demand-analysis',
  'm7-03-competition-analysis': '/content/modules/m7-product/03-competition-analysis',
  'm7-04-profit-screening': '/content/modules/m7-product/04-profit-screening',
  'm7-05-sourcing': '/content/modules/m7-product/05-sourcing',
  'm7-06-selection-practice': '/content/modules/m7-product/06-selection-practice',
  'pb-ads-00': '/content/playbooks/ads-16-tactics/index',
  'pb-ads-01': '/content/playbooks/ads-16-tactics/01-low-budget-bargain',
  'pb-ads-02': '/content/playbooks/ads-16-tactics/02-asin-targeting',
  'pb-ads-03': '/content/playbooks/ads-16-tactics/03-auto-ads-refinement',
  'pb-ads-04': '/content/playbooks/ads-16-tactics/04-ranking-push-and-risk',
  'pb-ads-05': '/content/playbooks/ads-16-tactics/05-peak-season-combo',
  'skill-ai-image': '/content/skills/ai-image-workflow',
  'skill-ai-keywords': '/content/skills/ai-selection-keywords',
  'skill-ai-ops': '/content/skills/ai-ads-ops',
  'skill-ai-rufus': '/content/skills/ai-listing-rufus',
  'skill-browser': '/content/skills/browser-shortcuts',
  'skill-domain': '/content/skills/domain-basics',
  'skill-excel': '/content/skills/excel-for-ops',
  'skill-phishing': '/content/skills/phishing-detection',
  'skill-shortcuts': '/content/skills/system-shortcuts',
}
// ===== 自动生成区块结束 =====

// ------------------------------------------------------------
// 课名 / 课序号 工具函数（后台展示用）
// 取不到时回退 lessonId，绝不报错
// ------------------------------------------------------------
export function getLessonTitle(id: string): string {
  return lessonTitles[id] || id
}

// 课序号 + 课名，如 'm4-04' → '5.4 BE ACOS'
// 无课名则回退课序号；连课序号都没有则回退 lessonId
export function getLessonLabel(id: string): string {
  const title = lessonTitles[id]
  const num = lessonNumbers[id]
  if (title && num) return `${num} ${title}`
  if (title) return title
  return id
}
